// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbuaEaliOrNvaaRRnCKEkwpNIDFa0xkz4',
    appId: '1:184475424927:web:31ecfc178bc5fdc1d42aaa',
    messagingSenderId: '184475424927',
    projectId: 'book-search-472921',
    authDomain: 'book-search-472921.firebaseapp.com',
    storageBucket: 'book-search-472921.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF-h7Mt_hqYq7JQEk6vYyENBQhiqujWdo',
    appId: '1:184475424927:android:c8079539a49dcba4d42aaa',
    messagingSenderId: '184475424927',
    projectId: 'book-search-472921',
    storageBucket: 'book-search-472921.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8DtEAEcGIE-DrP6kFbV08wbOb3P_Z1To',
    appId: '1:184475424927:ios:58036b4e426356e0d42aaa',
    messagingSenderId: '184475424927',
    projectId: 'book-search-472921',
    storageBucket: 'book-search-472921.firebasestorage.app',
    androidClientId: '184475424927-1jetlrmsa5otjfdf8r3qu69d5lnl0c2l.apps.googleusercontent.com',
    iosClientId: '184475424927-1gpfkbpnfhdp4qvd0bkgo65342m5h74q.apps.googleusercontent.com',
    iosBundleId: 'com.example.takt',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8DtEAEcGIE-DrP6kFbV08wbOb3P_Z1To',
    appId: '1:184475424927:ios:58036b4e426356e0d42aaa',
    messagingSenderId: '184475424927',
    projectId: 'book-search-472921',
    storageBucket: 'book-search-472921.firebasestorage.app',
    androidClientId: '184475424927-1jetlrmsa5otjfdf8r3qu69d5lnl0c2l.apps.googleusercontent.com',
    iosClientId: '184475424927-1gpfkbpnfhdp4qvd0bkgo65342m5h74q.apps.googleusercontent.com',
    iosBundleId: 'com.example.takt',
  );
}
