import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../models/curriculum_unit.dart';
import '../models/lesson_node.dart';
import '../services/curriculum_service.dart';
import '../services/vocabulary_service.dart';
import '../widgets/lesson_node_widget.dart';
import 'practice/gender_practice_screen.dart';
import 'practice/compound_practice_screen.dart';
import 'practice/sentence_practice_screen.dart';
import 'practice/vocabulary_practice_screen.dart';

/// The "Path" tab: a vertically scrolling, gently zig-zagging column of
/// lesson nodes generated by CurriculumService. See design doc §4.
class SkillTreeScreen extends StatefulWidget {
  const SkillTreeScreen({super.key});

  @override
  State<SkillTreeScreen> createState() => _SkillTreeScreenState();
}

class _SkillTreeScreenState extends State<SkillTreeScreen> {
  static const double _nodeRowHeight = 128;
  static const double _unitHeaderHeight = 76;
  static const double _unitSpacing = 16;
  static const List<double> _xFractions = [0.5, 0.78, 0.5, 0.22];

  int _dueCount = 0;

  @override
  void initState() {
    super.initState();
    _refreshDueCount();
  }

  Future<void> _refreshDueCount() async {
    final due = await VocabularyService().getDueWords();
    if (mounted) setState(() => _dueCount = due.length);
  }

  Future<void> _handleNodeTap(LessonNode node) async {
    if (node.type == LessonNodeType.story) {
      DefaultTabController.of(context).animateTo(1);
      await CurriculumService().completeNode(node.id);
      return;
    }

    Widget target;
    switch (node.type) {
      case LessonNodeType.vocab:
      case LessonNodeType.review:
        target = const VocabularyPracticeScreen();
        break;
      case LessonNodeType.gender:
        target = const GenderPracticeScreen();
        break;
      case LessonNodeType.compound:
        target = const CompoundPracticeScreen();
        break;
      case LessonNodeType.sentence:
        target = const SentencePracticeScreen();
        break;
      case LessonNodeType.story:
        return; // handled above
    }

    await Navigator.of(context).push(MaterialPageRoute(builder: (_) => target));
    await CurriculumService().completeNode(node.id);
    await _refreshDueCount();
  }

  @override
  Widget build(BuildContext context) {
    return Consumer<CurriculumService>(
      builder: (context, curriculum, _) {
        final units = curriculum.units;
        if (units.isEmpty) {
          return const Center(child: CircularProgressIndicator());
        }

        return LayoutBuilder(
          builder: (context, constraints) {
            final width = constraints.maxWidth;
            final children = <Widget>[];
            final centers = <Offset>[];

            double y = 24;
            int globalIndex = 0;

            for (final unit in units) {
              children.add(_buildUnitHeader(context, unit, y, width));
              y += _unitHeaderHeight;

              for (final node in unit.nodes) {
                final xFrac = _xFractions[globalIndex % _xFractions.length];
                final centerX = xFrac * width;
                final centerY = y + _nodeRowHeight / 2 - 14;
                centers.add(Offset(centerX, centerY));

                const nodeWidth = LessonNodeWidget.diameter + 24;
                children.add(
                  Positioned(
                    top: y,
                    left: centerX - nodeWidth / 2,
                    width: nodeWidth,
                    child: LessonNodeWidget(
                      node: node,
                      unitColor: unit.colorSeed,
                      dueCount: node.type == LessonNodeType.review ? _dueCount : null,
                      onTap: () => _handleNodeTap(node),
                    ),
                  ),
                );

                y += _nodeRowHeight;
                globalIndex++;
              }

              y += _unitSpacing;
            }

            final totalHeight = y + 24;

            return SingleChildScrollView(
              child: SizedBox(
                width: width,
                height: totalHeight,
                child: Stack(
                  children: [
                    CustomPaint(
                      size: Size(width, totalHeight),
                      painter: _PathPainter(
                        centers: centers,
                        color: Theme.of(context).dividerColor.withValues(alpha: 0.6),
                      ),
                    ),
                    ...children,
                  ],
                ),
              ),
            );
          },
        );
      },
    );
  }

  Widget _buildUnitHeader(BuildContext context, CurriculumUnit unit, double top, double width) {
    final theme = Theme.of(context);
    return Positioned(
      top: top,
      left: 24,
      right: 24,
      child: Row(
        children: [
          Container(
            width: 36,
            height: 36,
            decoration: BoxDecoration(
              color: unit.colorSeed.withValues(alpha: 0.15),
              shape: BoxShape.circle,
            ),
            child: Icon(unit.icon, color: unit.colorSeed, size: 18),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Text(
              unit.title,
              style: theme.textTheme.titleSmall?.copyWith(
                fontWeight: FontWeight.bold,
                color: theme.colorScheme.onSurface,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _PathPainter extends CustomPainter {
  final List<Offset> centers;
  final Color color;

  _PathPainter({required this.centers, required this.color});

  @override
  void paint(Canvas canvas, Size size) {
    if (centers.length < 2) return;

    final paint = Paint()
      ..color = color
      ..strokeWidth = 5
      ..style = PaintingStyle.stroke
      ..strokeCap = StrokeCap.round;

    final path = Path()..moveTo(centers.first.dx, centers.first.dy);
    for (var i = 1; i < centers.length; i++) {
      final prev = centers[i - 1];
      final cur = centers[i];
      final controlPoint = Offset(prev.dx, (prev.dy + cur.dy) / 2);
      final controlPoint2 = Offset(cur.dx, (prev.dy + cur.dy) / 2);
      path.cubicTo(controlPoint.dx, controlPoint.dy, controlPoint2.dx, controlPoint2.dy, cur.dx, cur.dy);
    }

    canvas.drawPath(path, paint);
  }

  @override
  bool shouldRepaint(covariant _PathPainter oldDelegate) {
    return oldDelegate.centers != centers || oldDelegate.color != color;
  }
}
